# Shown below are some global variables, you could use it in all scripts.
# $PLATFORM: platform to build sdk(e.g. linux)
# $CONFIG: config to build sdk(e.g. full)
# $BUILD_OPTS: options to build(e.g. --cfg="xxx")
language: cpp
platform:
        windows:
                env: windows
                build:
                        scripts:
                                - echo "Building Windows"
                                - rm -rf install target deps
                                - cppbuild env
                                - cppbuild dep $BUILD_OPTS
                                - TARGET_ARCH=x86_64 cppbuild build --build-type=release --install
                                - TARGET_ARCH=x86 cppbuild build --build-type=release --install
                                - rake package
        linux:
                env: linux
                build:
                        scripts:
                                - echo "Building Linux"
                                - rm -rf install target deps
                                - cppbuild env
                                - cppbuild dep $BUILD_OPTS
                                - cppbuild build --build-type=release --install
                                  #- TARGET_ARCH=x86 cppbuild build --build-type=release --install
                                - TARGET_ARCH=armv7 cppbuild build --build-type=release --install
                                - rake package
        android:
                env: linux
                build:
                        scripts:
                                - echo "Building Android"
                                - rm -rf install target deps
                                - cppbuild env
                                - cppbuild dep $BUILD_OPTS
                                - TARGET_OS=android TARGET_ARCH=armv7 cppbuild build --build-type=release --install
                                - TARGET_OS=android TARGET_ARCH=aarch64 cppbuild build --build-type=release --install
                                  #- TARGET_OS=android TARGET_ARCH=x86 cppbuild build --build-type=release --install
                                - rake package
        ios:
                env: darwin
                build:
                        scripts:
                                - echo "Building iOS"
                                - rm -rf install target deps
                                - cppbuild env
                                - cppbuild dep $BUILD_OPTS
                                - TARGET_OS=ios_os TARGET_ARCH=universal cppbuild build --build-type=release --install
                                  #- TARGET_OS=ios_sim TARGET_ARCH=universal cppbuild build --build-type=release --install
                                - rake package
config:
        ppl:
                platforms:
                        - platform: windows
                          default: true
                        - platform: linux
                          default: true
                        - platform: android
                        - platform: ios
                options: ""
        caffe:
                platforms:
                        - platform: windows
                          default: true
                        - platform: linux
                          default: true
                        - platform: android
                        - platform: ios
                options: "--cfg='-use_ppl'"

```


# .autobuild.yml


```

language: cpp
jobs:
        windows-x86_64:
                env: win64
                script:
                        - echo "Building Windows 64bit"
                        - rm -rf install
                        - cppbuild env
                        - cppbuild dep || exit 1
                        - TARGET_ARCH=x86_64 cppbuild test --no-run --release
                test:
                        - rm -rf target/tmp
                        - rake get_models
                        - PATH=target/windows-x86_64/test/src/Release:$PATH TARGET_ARCH=x86_64 cppbuild test --release || exit 1
                clean:
                        - rm -rf deps
                        - git clean -xdf
        linux-x86_64:
                env: linux
                script:
                        - set -e
                        - echo "Building Linux 64bit"
                        - rm -rf install
                        - cppbuild env
                        - cppbuild dep
                        - cppbuild test --no-run
                test:
                        - rm -rf target/tmp
                        - rake get_models
                        - cppbuild test
                clean:
                        - rm -rf deps
                        - git clean -xdf
        linux-x86:
                env: linux
                script:
                        - set -e
                        - echo "Building Linux 32bit"
                        - rm -rf install
                        - cppbuild env
                        - cppbuild dep
                        - TARGET_ARCH=x86 cppbuild test --no-run
                test:
                        - rm -rf target/tmp
                        - rake get_models
                        - TARGET_ARCH=x86 cppbuild test
                clean:
                        - rm -rf deps
                        - git clean -xdf
        linux-armv7:
                env: linux-armv7
                script:
                        - set -e
                        - echo "Building Linux-armv7"
                        - rm -rf install
                        - cppbuild env
                        - cppbuild dep
                        - TARGET_OS=linux TARGET_ARCH=armv7 cppbuild test --no-run
                test:
                        - rm -rf target/tmp
                        - rake get_models
                        - echo "Run on TK1"
                        - "LD_LIBRARY_PATH=target/linux-armv7/test target/linux-armv7/test/test_sdk_common"
                clean:
                        - rm -rf deps
                        - git clean -xdf
        android:
                env: linux
                script:
                        - set -e
                        - echo "Building Android"
                        - rm -rf install
                        - cppbuild env
                        - cppbuild dep
                        - TARGET_OS=android TARGET_ARCH=armv7 cppbuild build --build-type=release --install
                        - TARGET_OS=android TARGET_ARCH=aarch64 cppbuild build --build-type=release
#                        - TARGET_OS=android TARGET_ARCH=x86 cppbuild build --build-type=release
                clean:
                        - rm -rf deps
                        - git clean -xdf
        macos:
                env: darwin
                script:
                        - echo "Building iOS"
                        - rm -rf install
                        - cppbuild env
                        - cppbuild dep || exit 1
                        - TARGET_OS=ios_sim TARGET_ARCH=universal cppbuild build --build-type=release || exit 1
                        - TARGET_OS=ios_os TARGET_ARCH=universal cppbuild build --build-type=release || exit 1
                clean:
                        - rm -rf deps
                        - git clean -xdf


